### ISSUE TITLE
[be][bug] front dockerfile 수정

### ISSUE THREAD

**Issue by yonghwankim-dev** [masters2023-3rd-project-bugbusters/issue-tracker-max#170]
## 상황
- 이슈 목록 화면 이동시 빈화면이 나옵니다.

## 원인
- npm run dev로 실행시 msw 목서버가 실행됩니다.

## 해결방법
- docker-compose로 실행시 리액트 컨테이너의 환경변수 NODE_ENV=prod로 설정합니다.
- 내부 코드에서 NODE_ENV=="development"인 경우 msw 목서버가 실행되도록 하고 있습니다.
```
version: "3.8"
services:
  app:
    container_name: issue_tracker_app_dev
    image: yhkim951107/issue_tracker_app_dev:latest
    ports:
      - 8080:8080
    volumes:
      - issue_tracker_app_dev:/app
  web:
    container_name: issue_tracker_web_dev
    image: yhkim951107/issue_tracker_web_dev:latest
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=prod
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - app
volumes:
  issue_tracker_app_dev:

```
