### ISSUE TITLE
[be][bug] spring 실행시 AWS 인가 문제 해결

### ISSUE THREAD

**Issue by yonghwankim-dev** [masters2023-3rd-project-bugbusters/issue-tracker-max#187]
## 상황
- SPRING 서버 실행시 AWS 인가 문제 예외가 발생합니다. 그러나 다른 기능 수행에는 이상 없어 보입니다.

## 원인
- AWS SDK를 사용하는 애플리케이션에서 EC2 인스턴스의 메타데이터에 접근을 시도할 때 발생하는 문제로 보입니다. 

## 해결방법
EC2 인스턴스가 아닌 다른곳에서 해당 애플리케이션을 실행할 때는 시스템변수 "com.amazonaws.sdk.disableEc2Metadata"에 값을 true로하거나 환경변수 "AWS_EC2_METADATA_DISABLED" 값을 true로 해주면 된다.

```
@SpringBootApplication
public class BackendApplication {

	static {
		System.setProperty("com.amazonaws.sdk.disableEc2Metadata", "true");
	}

	public static void main(String[] args) {
		SpringApplication.run(BackendApplication.class, args);
	}

}
```

application.yml
```
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
```
